### ISSUE TITLE
Necesitamos tu ayuda para poder seguir desarrollando este addon

### ISSUE THREAD

**Issue by Paco8** [Paco8/plugin.video.movistarplus#1]
Este addon ha sido posible realizarlo gracias a una persona que compartía su abono conmigo. Esa persona se ha dado de baja, así que me temo que ya no podré seguir actualizándolo (yo estoy abonado a Orange).

Si alguien más se ofrece a compartir su abono a M+ se lo agradecería mucho y podría continuar mejorando el addon.
Es muy fácil solo tendrías que mandarme el fichero key que se obtiene con la opción **Exportar token de acceso a fichero key** en el menú Cuentas del addon. Este fichero key no contiene ni tu nombre de usuario ni tu clave. Con ese token de acceso podría acceder a tu abono solo desde Kodi, no podría entrar ni en la web ni en ninguna de las aplicaciones.

Si te animas puedes mandar ese fichero key a este email: mitvbox.spain arroba gmail.com o a discord: [Paco8#1670](https://discord.com/users/1027140600925016065)

**Comment by mohcenben** [comment]
Buenas queria preguntarte lo del error 4027 como podria resolverse? el proxy es que no se que habria que hacer en el proxy

**Comment by mohcenben** [comment]
De acuerdo gracias has hecho muy buen trabajo eh Paco!!! sigue asi
No cabria la posibilidad para dazn?

**Comment by Paco8** [comment]
Creo que ya existe un addon para dazn. Está en el repositorio oficial de Kodi.

**Comment by mohcenben** [comment]
![image](https://user-images.githubusercontent.com/73310192/226878791-ddf0212a-b34a-470b-9382-c9ad40769f3f.png)


Sabes el motivo acerca de esto?

**Comment by mohcenben** [comment]
No funcionaria con reinstalar la aplicacion?

**Comment by mohcenben** [comment]
![image](https://user-images.githubusercontent.com/73310192/226905375-46ac3c48-651f-4109-9a62-f35209f122c6.png)

**Comment by mohcenben** [comment]
No se si eso servira

**Comment by perro130** [comment]
Hola qué novedades trae la nueva versión

**Comment by Paco8** [comment]
Poca cosa. He visto que la pista de audio con audiodescripción aparecía como "desconocida" en kodi, lo he arreglado.

**Comment by perro130** [comment]
Gracias  no tendrías Telegram por comentar algo

**Comment by perro130** [comment]
Veo versión 074 .
Como avanza esto
