### ISSUE TITLE
ADDON DAZN

### ISSUE THREAD

**Issue by Demiurgo0** [Paco8/plugin.video.movistarplus#11]
Buenas.

Magnifico trabajo!! Creara un addon igual que el de Movistar pero para Dazn? Seria una gran noticia!!.

muchas gracias por todo

**Comment by Paco8** [comment]
Creo que ya hay un addon de dazn ¿no?

**Comment by Demiurgo0** [comment]
Pero no es como el tuyo de movistar no? Que se pueda ver en mas dispositivos... y mas

**Comment by Paco8** [comment]
Pero tampoco puedo hacer magia. Si dazn comprueba, por ejemplo, la ip (que no lo sé) para limitar visionados simultáneos pues no hay manera de saltárselo.
