### ISSUE TITLE
Acceso por Key

### ISSUE THREAD

**Issue by miguelthepooh** [Paco8/plugin.video.movistarplus#14]
Por favor, podrías explicar más detalladamente el procedimiento para hacer acceso por key

¿Dónde está el token de acceso y en qué carpeta se tiene que guardar?

Muchas gracias

**Comment by Paco8** [comment]
Si has iniciado sesión con usuario y clave te saldrá una opción para exportar el token en un fichero key. Lo puedes guardar donde quieras, lo puedes usar en otro aparato para iniciar sesión.

**Comment by miguelthepooh** [comment]
Muchas gracias por tu respuesta @Paco8

La he entendido perfectamente.

Mi dificultad con el usuario y clave es que para visitar la web ver.movistarplus.es, y tener el deco de movistar en la misma red, la web me autologuea sin yo tener que poner mi usuario ni mi clave.

Mirando en la web el usuario soy "9xxzzzww8@Telefon..." sin terminar de ver el nombre completo de mi usuario y la clave no me la muestra. 9xxzzzww8 es mi numero de linea fija al que está el contrato telefónico.

Y de ahí no salgo. 

Creo entender que el token es un archivo tipo cnf, ¿sabes donde se guarda en firefox-linux? ¿se puede copiar tal cual o el proceso de convertirlo en el archivo movistarplus.key es más complicado que hace copypaste?

Saludos y gracias

**Comment by Paco8** [comment]
Puedes probar este programa, para tratar de sacar el token:
https://github.com/Paco8/MSAuthenticationKey

**Comment by miguelthepooh** [comment]
Muchas gracias @Paco8 lo pruebo en unos días, estoy fuera de casa y lo pruebo en cuanto llegue

Saludos
