### ISSUE TITLE
Canales UHD no disponibles

### ISSUE THREAD

**Issue by dmnmsc** [Paco8/plugin.video.movistarplus#16]
Hola,

Han añadido canales UHD para liga y champions en la app de Android TV. Sería posible visualizarlos con este addon? El dispositivo que carga por defecto el addon es PC/MAC. No sé si ese puede ser el problema.

Muchas gracias.

**Comment by Paco8** [comment]
¿Se pueden ver esos canales en un PC? 
El addon saca los datos de la página web. Si los canales solo se pueden ver en la app de Android TV habría que analizar lo que hace pero eso ya es más complicado.

**Comment by dmnmsc** [comment]
No, en la web no aparecen esos canales. Y el único modo de acceder con un PC es a través de la página web. No sé si puede configurar el addon para que use la sesión de Android TV en vez de la sesión PC/MAC.

**Comment by Paco8** [comment]
Probando cosas a voleo he conseguido sacar la lista de canales para Android TV, pero no hay ningún canal de la liga ni de champions ni ningún UHD. 
¿Exactamente en qué dispositivos están esos canales?

**Comment by dmnmsc** [comment]
Hola,

A mí me salen tanto en la app del Fire TV como en la app de Tizen. No sé si aparecen en todas las Android TV o si lo van implementando poco a poco. En mi caso, los canales UHD salen al final de todo: Liga, Champions y F1.

**Comment by Paco8** [comment]
Los canales UHD ya deben salir en la versión 0.7.14. Hay que tener en cuenta que el plugin actualiza el listado de canales cada 24 horas, por lo que es posible que no os salgan inmediatamente.

El canal Dazn F1 4k no se ve, quizás por este problema: https://github.com/Paco8/plugin.video.movistarplus/issues/18

**Comment by maikeln80** [comment]
> Los canales UHD ya deben salir en la versión 0.7.14. Hay que tener en cuenta que el plugin actualiza el listado de canales cada 24 horas, por lo que es posible que no os salgan inmediatamente.
> 
> El canal Dazn F1 4k no se ve, quizás por este problema: #18

muchas gracias, efectivamente ya aparecen, el problema de dazn es que necesita el encabezado con el x-tcdn-token para funcionar, por lo menos en la version HD

**Comment by Paco8** [comment]
En la versión 0.7.16 hay que activar la opción 4K en los ajustes para que aparezcan los canales UHD.
