### ISSUE TITLE
No compatible con VPN

### ISSUE THREAD

**Issue by magamess** [Paco8/plugin.video.movistarplus#17]
Buenas Paco,

En primer lugar, muchas gracias por el add-on.

Tengo una subscripción de Movistar+, pero como resido en Reino Unido tengo que usar una VPN para poder acceder al contenido de Movistar+.

Pero desde hace 1 mes, movistar detecta que estoy usando una VPN y no me deja ver ningún Canal en Directo. He probado con 3 empresas de VPN distintas (de las de pago) y no ha habido suerte con ninguna.

He probado tu add-on y tampoco funciona (lo mismo pasa con Simple IPTV), se te ocurre alguna forma de evitar el bloqueo de VPN que ha puesto Movistar+?

Gracias y perdona las molestias!

**Comment by Paco8** [comment]
Pues lo único que se me ocurre es que uses otro VPN que no sea detectado por M+

**Comment by magamess** [comment]
Buenas Paco, he probado 5 compañías distintas (NordVPN, Surfshark, ExpressVPN, Mullvad y Proton VPN) y no ha habido suerte con ninguna. De todas formas, gracias por contestar!

**Comment by Paco8** [comment]
Se me ocurre que si tienes un familiar en España que le podrías pedir que se instale un servidor VPN privado en algún aparato. Eso no creo que lo puedan detectar.

**Comment by magamess** [comment]
Si, eso que comentas es una opción que había pensado, tengo que ver como se hace, ya que no tengo experiencia. Estas Navidades cuando vaya por casa de mis padres lo intentaré, quizás pueda dejar un móvil antiguo siempre encendido para que éste haga de servidor, pero no se si se podrá hacer eso con Android o lo ideal seria un PC.

**Comment by magamess** [comment]
> Hola,en la casa donde este contratado hay que montar un servidor VPN (wireguard o el que quieras) y tu conectarte. Yo lo hago asi para ver el futbol en Smart TV

Buenas vrevert, gracias por el mensaje. Es justo lo que quiero hacer, te importaría explicarme un poco como has montado el servidor, o si tienes algún enlace de alguna web que lo explique como hacerlo? Perdona las molestias, es que he buscado bastante y no llego a encontrar como hacer ese servidor desde casa de mis padres en España.

He probado a crearme una VPN privada con OpenVPN (usando Oracle Cloud con servidor en Madrid) y no funciona, me sigue detectado que estoy conectado a una VPN...

Encontré también la opción de Tailscale, pero no sé si es eso lo que necesito para este caso concreto.

Muchas gracias!

**Comment by vrevert** [comment]
Hola, yo lo tengo montado en el router Asus que gestiona la conexion en mi casa. Tambien he usado Openvpn desde el Asus, otra opcion es usar una rapberry pi para que haga de servidor. Te dejo enlace a una guia para instalar en raspberry. [https://dev.to/nervi0s/wireguard-con-raspberry-pi-3i60](url)
Yo esta semana he estado fuera y he visto los canales de futbol sin ingun problema,  capados fuera de casa en dispositivos tipo firetv o Google  Chromecast. En ambos casos la  app wireguard disponible en las tiendas de apps.

Saludos.
