### ISSUE TITLE
script para obtener x-tcdn-token

### ISSUE THREAD

**Issue by maikeln80** [Paco8/plugin.video.movistarplus#19]
Hola, se podría mediante un script exportar el valor x-tcdn-token que es necesario para poder ver los canales que actualmente necesitan ese encabezado para que funcionen, entre ellos m+ cine o los deportes, gracias.

**Comment by Paco8** [comment]
La cosa es averiguar de dónde sale el x-tcdn-token. Supongo que de algún encabezado de una página que carga antes.

**Comment by maikeln80** [comment]
Una vez dentro de la pagina y logueado al ir al canal te muestra ese encabezado
