### ISSUE TITLE
Login con .key

### ISSUE THREAD

**Issue by exdelins** [Paco8/plugin.video.movistarplus#20]
Buenas tardes
Por favor, podría darme más información de como funciona el login con .key? 
La clave que está en el .key no es el token bearer verdad? Podría ayudarme a comprender su funcionamiento?
Gracias

**Comment by Paco8** [comment]
Primero inicias sesión con usuario y clave. Luego puedes exportar el token a un fichero key. Con ese fichero key puedes iniciar sesión más tarde en ese u otro aparato con la opción iniciar sesión con fichero key.

El origen de esta opción es que al principio de todo no era posible iniciar sesión con usuario y clave, había que sacar el token del navegador y luego iniciar sesión con el fichero key en el plugin. Ahora mismo ya no es muy útil esta opción.

**Comment by exdelins** [comment]
Gracias por la respuesta
Podría profundizar técnicamente ?
Con el fichero key a que servicio invoca y con que datos de entrada (entiendo que el token ) para poder hacer login ? Que recupera para que funcione ? 
gracias por su tiempo
