### ISSUE TITLE
Cortes y reproduccion en SD en raspberry pi libreelec

### ISSUE THREAD

**Issue by Alfomso51** [Paco8/plugin.video.movistarplus#21]
Hola un saluda, lo primero mil gracias por este fantastico addon.
 Mi problema es el siguiente, lo tengo instalado en una raspberry pi 4b de 4 de ram con libreelec y la reproduccion se corta a los pocos instanstes. E configurado el bufer con luar y sigue igual e probado a bajar la resolucion de kodi y lo mismo, no consigo que la reproduccion sea fluida y constante, e probado de todo y la cosa sigue igual, e de decir que la tengo por wifi y tengo una muy buena conexion, tampien probe por ethernet y la cosa incluso es peor, algun alma caritativa que me heche una manita porfi

**Comment by Alfomso51** [comment]
Aaa se me paso comentar que hay algunos canales que se ven en sd y no en hd

**Comment by Paco8** [comment]
Si se ven en SD eso ya debe ser cosa de la configuración de inputstream adaptive. Si te llega baja velocidad supongo que te estará escogiendo un stream en SD.

**Comment by Alfomso51** [comment]
Hola muchas gracias por contestar, al fin di con la solucion la pongo por si acaso le pasa a alguien y fue la cosa mas simple del mundo, pues me pasaba lo mismo en todos los dispositivos que tengo kodi, y la solucion fue hacerle al ruter de movistar un reset de fabrica, desde que se la hice ahora va de lujo e incluso los canales se ven en HD y sin ningun tiron

**Comment by Alfomso51** [comment]
de nuevo muchas gracias por este fantastico curro, tengo otra pregunta, ¿seria posible que la epg descargue las caratulas de los programas y la informacion?

**Comment by Paco8** [comment]
Activa la opción "Descargar información extra" en los ajustes del addon. Pero puede ser muy lento...

**Comment by Alfomso51** [comment]
hola buenas, no consigo que descargue las caratulas, tengo una consulta ahora en la raspi  al seleccionar un canal se congela a los pocos segundo lo detengo le vuelvo a dar y funciona perfectamente durante todo el tiempo que lo este usando, pero si reinicio la raspi vuelve a pasar ¿alguna idea de por que sucede esto? en los demas dispositivos ahora funciona perfectamente

**Comment by Paco8** [comment]
Si te refieres a la epg que se exporta para el IPTV Simple, no, ahí no hay carátulas ni descripción de los programas, porque sería lentísimo, habría que descargar la ficha de cada programa.

Supongo que editando el m3u8 del fichero de canales se podrá cambiar el nombre de los canales.

**Comment by Paco8** [comment]
Que se pare cada pocos segundos creo que lo he experimentado yo en un firestick antiguo, con kodi 20. Creo que ocurre si el inputstream está configurado en modo adaptativo. Yo lo tengo puesto en "OSD manual", creo que así va mejor.

En cuanto a lo del m3u8, no actives en el addon la opción de exportar los canales automáticamente para que no sobrescriba tus cambios.

**Comment by Alfomso51** [comment]
Ok muchas gracias, mañana lo mirare que ahora estoy currando y te cuento, pido disculpas por si soy muy cansino.

**Comment by Alfomso51** [comment]
nada, no hay manera, en windows dura algo mas pero sigue igual y donde a mi mas me interesa que es en la raspberry la cosa a mejorado muy poco sigue teniendo parones

**Comment by Paco8** [comment]
Es raro que ni siquiera en Windows te funcione bien. ¿Has probado con kodi 19 por si acaso?

**Comment by Alfomso51** [comment]
Hola buenas, lo primero disculparme por si e sido un pesado
Mira anoche se me encendio la neurona dandole vueltas pense que todo el fallo de la raspi podria darse por la micro sd, asi que aprobechabdo que tenia por hay un ssd de 128gb decidi instalar libreelec en el ssd y iniciar la raspi desde el sd.
Y tachan... se hizo el milagro, aparte de que kodi va como un tiro tu addon funciina de maravilla a 1080p y se ve de lujo sin ningun tiron y lo de la epg que comentaba segui tu consejo y ahora salen todos los canales en la guia y con 7 dias atras para usar los U7D desde el epg y 15 dias en adelante pues la raspi no tengo intencion de apagarla nunca.
Con el de windows sigue mas o menos igual pero investigare por hay y si encuentro la solucion la compartire por aqui como lo de la raspi.
Y con lo de android tv lo intentare tambien a ver si lo consigo.
Vuelvo a darte las gracias y a animarte con este fantastico curro
