### ISSUE TITLE
No veo directo si TV a la carta 

### ISSUE THREAD

**Issue by Comoera** [Paco8/plugin.video.movistarplus#22]
Buenas, soy nuevo en esto y algo debo tener mal configurado, veo TV a la cartas al meter usuario y clave pero no puedo ver canales

**Comment by Paco8** [comment]
¿Da algún error?

**Comment by Comoera** [comment]
No me sale error alguno, solo al abrir no carga nada , como carpeta vacía

**Comment by Paco8** [comment]
Quizás no se haya descargado correctamente el fichero de canales. Puedes probar a borrar los ficheros channels* con el explorador de archivos del kodi, en carpeta del perfil, addon_data, plugin.video.movistarplus
