### ISSUE TITLE
#Vamos no se ve en 1080p (Full HD) Solo 720p

### ISSUE THREAD

**Issue by RafaelR11** [Paco8/plugin.video.movistarplus#25]
#Vamos no se ve en 1080p en el addon. Lo máximo es 720p.
Con los demás canales prácticamente todos tienen 1080p.

**Comment by Paco8** [comment]
Que yo sepa es así. En el manifest la resolución más alta de este canal es 1280x720.

**Comment by Paco8** [comment]
He conseguido sacar la lista de canales para Android TV pero el canal Vamos sigue a 720p y no veo cambios en el bitrate. La diferencia es que en esa lista no están los canales de fútbol.

**Comment by pmsobrado** [comment]
Que raro, pero yo me refería al VOD. ¿Has podido probar con eso, a ver si aparece un nuevo perfil con bitrate superior a 5000?

**Comment by smplayer-dev** [comment]
> Que raro, pero yo me refería al VOD. ¿Has podido probar con eso, a ver si aparece un nuevo perfil con bitrate superior a 5000?

Pues parece que lo he encontrado. Prueba esta versión:
[plugin.video.movistarplus-0.8.6.zip](https://github.com/Paco8/plugin.video.movistarplus/files/13862793/plugin.video.movistarplus-0.8.6.zip)

**Comment by Paco8** [comment]
Prueba esta versión: 
[plugin.video.movistarplus-0.8.6.zip](https://github.com/Paco8/plugin.video.movistarplus/files/13862920/plugin.video.movistarplus-0.8.6.zip)

**Comment by pmsobrado** [comment]
@Paco8 lo he probado y el máximo de VOD sigue siendo 5000. Y te digo más, he probado la serie "El otro lado" en la app oficial en Android TV y esta tiene UHD y es 4K, otro perfil oculto más xDD

Sobre el canal Vamos, lo he probado y sigue a 720p, en mi opinión es algo de ellos, en la app móvil/web quizá es lo máximo que están mandando.

Sobre el VOD, definitivamente existe el perfil 1080p a más de 5000 de bitrate, 7000 y pico si no recuerdo mal (conozco a gente que lo ha sacado, pero yo no se como), y otro perfil 4K HDR, pero bueno, ni es el asunto principal de esta issue, ni se si estarás interesado en explorar esta opción, seguramente sea un engorro. Yo lo decía por aportar, y si no es muy dificil, incorporarlo, pero tu mismo :)

Un saludo.

**Comment by Paco8** [comment]
Con esa versión me sale un stream de 8000 en las películas:

![IMG_20240108_201725_076](https://github.com/Paco8/plugin.video.movistarplus/assets/5084042/f16daff5-3f5d-42ba-a221-1b4ba1f8439b)

El 4K está soportado también, pero hay que activarlo en los ajustes.

**Comment by pmsobrado** [comment]
Probaré a activarlo, a ver si así me salen más perfiles. ¿Cual ha sido la manera de obtener esos perfiles extra al final? ¿Mandando un parámetro especial?

**Comment by Paco8** [comment]
Cambiando en las urls "webplayer" por "android.tv".

**Comment by pmsobrado** [comment]
Vale, he conseguido encontrar un perfil con un bitrate de 8000, pero para la serie "El otro lado" sigo sin ver un perfil 4K en el manifest... ni idea de como lo harán en la app la verdad.

Gracias por la info.

**Comment by Paco8** [comment]
Esto es con la serie "El otro lado", activando el 4K en los ajustes:

![Captura desde 2024-01-09 11-20-17](https://github.com/Paco8/plugin.video.movistarplus/assets/5084042/669552af-3271-4d0e-8c9a-4bd3fa635afb)

**Comment by Paco8** [comment]
Para el 4K hay que añadir `&filterQuality=UHD` a la url.

**Comment by pmsobrado** [comment]
Ahhhmigo, eso era, muchas gracias jejeje.

**Comment by Paco8** [comment]
Y sobre el canal Vamos, yo creo que es así, a 720p.

**Comment by magamess** [comment]
Buenas! 

Perdonad, una consulta. Como cambio las urls "webplayer" por "android.tv"? Se hace desde Kodi? He estado buscado en los ajustes del addon pero no lo encuentro. Gracias!

**Comment by Paco8** [comment]
No tienes nada que hacer. El addon ya lo hace.

**Comment by pmsobrado** [comment]
Que raro, a mi si me salió 4K y HDR. ¿El dispositivo que usas tiene widevine L1?

**Comment by magamess** [comment]
Estoy usando un Chromecast 4K con Google TV. Usando la App nativa de Movistar si que puedo verlo a mayor resolución

**Comment by Paco8** [comment]
Mira la configuración del inputstream adaptive, igual tienes una resolución fija.

**Comment by magamess** [comment]
Vale, inputstream adaptive lo tenía en Adaptativo, lo he cambiado a "OSD Manual" y con eso ya puedo verlo a mayor calidad
