### ISSUE TITLE
Guía ECG, se queda vacía a los dos dias

### ISSUE THREAD

**Issue by dcbsant** [Paco8/plugin.video.movistarplus#29]
Hola,

Lo primero, gracias por los plugin. Un lujo.

Te cuento mi problema.

La aplicación funciona perfectamente. El problema lo tengo con Iptv. Lo configuro y todo bien, pero al cabo de un par de días, la guía aparece vacío. Lo configuro de nuevo y perfecto dos o tres días más hasta que vuelve a entrar a la guía y vuelve a aparecer vacía. Unas veces funciona al entrar a la confirmación de la EPG y salir a la primera, otras a la segunda, otras al reiniciar kodi. La verdad es que no pillo el patrón.

Kodi está en la última versión. Iptv client también. Los plugin también….

Soy un inútil tecnológico así que seguro que no he configurado correctamente. Que estoy haciendo mal?

Gracias por la ayuda.

**Comment by Paco8** [comment]
¿Tienes activada en los ajustes del addon la opción de exportar los canales y la guía automáticamente?

**Comment by dcbsant** [comment]
> ¿Tienes activada en los ajustes del addon la opción de exportar los canales y la guía automáticamente?
> 
> 

Si. Están activados.

**Comment by Paco8** [comment]
Pues he estado probando esa opción unos días y de momento a mí la epg no me desaparece.
Pero el problema podría ser debido a que algún día la epg no se haya podido descargar correctamente porque los servidores de m+ fallan mucho.

**Comment by dcbsant** [comment]
No creo que sea eso... es algo que me pasa desde el primer día y no falla. Cada dos o tres días, lo mismo.

Parece que soy al único que le pasa así que voy a probar a desinstalar todo y volver a instalar.

Ya te cuento como ha ido.

Gracias.

**Comment by Paco8** [comment]
¿En qué dispositivo te ocurre esto? ¿Qué versión del kodi tiene?

**Comment by dcbsant** [comment]
Hola,

Dispositivo NVIDIA SHIELD TV

Kodi: última versión.

He desinstalado KODI y he reinstalado la última versión desde la playStore. He instalado los plugin de Movistar tal y como se indica. 

Ha funcionado de primeras y a los dos días, lo mismo, agenda vacía. 

No se si será problema de mi dispositivo. del IPTV Client.... ni idea.

Gracias.

**Comment by Paco8** [comment]
Lo probaré unos días con Kodi 20, y a ver qué pasa.

**Comment by dcbsant** [comment]
Genial. Te lo agradezco.

El addon de Movistar funciona perfectamente así que he pensando que podía ser problema del IPTV CLIENT, he intentado configurar otro cliente IPTV pero no he sido capaz de hacerlo funcionar.

Muchas gracias por tu ayuda.

**Comment by Paco8** [comment]
Lo que puede pasar es que si no entras todos los días en Kodi te encuentres la epg vacía, porque en primer lugar se ejecuta el IPTV Simple Client (cargando los datos del epg del día anterior) y luego el addon de movistar, exportando la guía (pero el IPTV Simple Client no se da cuenta y no la recarga).

**Comment by curro88** [comment]
Buenas!

A mi me pasa lo mismo desde hace un tiempo. Al principio viendo que nadie había reportado nada lo que hice fue desactivar y volver a activar el addon y nada. Probé reiniciando Kodi y tampoco. Tras varios intentos lo dejé y al día siguiente volvieron. Así llevo por lo menos 1 mes pero he estado muy liado y me ha sido imposible subir un log.

Tengo Kodi 20.3 como Launcher en mi Sony XH90.

Espero que puedas dar con el fallo.

Un saludo!

**Comment by dcbsant** [comment]
> Lo que puede pasar es que si no entras todos los días en Kodi te encuentres la epg vacía, porque en primer lugar se ejecuta el IPTV Simple Client (cargando los datos del epg del día anterior) y luego el addon de movistar, exportando la guía (pero el IPTV Simple Client no se da cuenta y no la recarga).

No, no creo que sea eso. Entro todos los días. Prefiero verlo en KOVI que en la aplicación Movistar+ (me gusta más tu pluging).

El problema parece estar en IPTV porque cuando se ha quedado la EPG vacía, descargo la guía, entro a la sección EPG, y en  "Ruta XMLTV" vuelvo a seleccionar el fichero movistar-epg.xml. Lo malo es que lo tengo que hacer continuamente.

No se puede configurar la guia en otro cliente IPTV?

Gracias.

**Comment by dcbsant** [comment]
> Buenas!
> 
> A mi me pasa lo mismo desde hace un tiempo. Al principio viendo que nadie había reportado nada lo que hice fue desactivar y volver a activar el addon y nada. Probé reiniciando Kodi y tampoco. Tras varios intentos lo dejé y al día siguiente volvieron. Así llevo por lo menos 1 mes pero he estado muy liado y me ha sido imposible subir un log.
> 
> Tengo Kodi 20.3 como Launcher en mi Sony XH90.
> 
> Espero que puedas dar con el fallo.
> 
> Un saludo!
> 
> PD: Adjunto log que justo me acabo de encontrar con la guía vacía [https://gist.github.com/curro88/557d54d7b15eac4616c888cc9e54b2f8](url)

Hola,

Pues no soy el único. 

Lo más que he conseguido es:

- Volver a descargar manualmente la guía
- Entrar a la sección EPG, y en  "Ruta XMLTV" volver a seleccionar el fichero movistar-epg.xml.

Y normalmente se vuelve a recargar todo.

Lo curioso es que siempre se empieza a vaciar por la noche, a partir de las 00.00. Es decir, sale la guía de todo lo que haya empezado antes de las 00.00 y a partir de ahí se ve vacío. Y claro, a partir de que se haya acabado eso que salía, ya todo vacío.

**Comment by dcbsant** [comment]
Así es como veo la guía a esta hora... 18:09....

![image](https://github.com/Paco8/plugin.video.movistarplus/assets/731058/b7eccddd-8e2a-45e0-a7f2-576b6ed6a7b5)

Esta noche, me va a volver a fallar. He adelantado hasta las 00.00 y.......

![image](https://github.com/Paco8/plugin.video.movistarplus/assets/731058/f2ab2c3a-ed9b-41c3-a384-1d0f9ed43276)

**Comment by CarlosRodriguez1982** [comment]
En que quedó esto?

**Comment by Paco8** [comment]
Quedó en que a mí el problema no me pasa. De todas formas a lo mejor ahora puedo hacer que se exporten los datos de la epg de manera diferente (y con más días) y a ver qué pasa.

**Comment by CarlosRodriguez1982** [comment]
Ahh esta bien. Me encanta usarla por EPG, para mi la manera más rápida de encontrar contenido. El mando del Tivo del ONO para mi es buenisimo, y poder usarlo con el FLIRC y con este addon es darle una vida nueva a la tele.

**Comment by Paco8** [comment]
¿Podéis probar esta versión?
[plugin.video.movistarplus-0.8.15.zip](https://github.com/Paco8/plugin.video.movistarplus/files/14435963/plugin.video.movistarplus-0.8.15.zip)

Se podrían poner más, pero de momento he puesto que se descarguen 4 días, para probar.

**Comment by dcbsant** [comment]
Como tengo problemas con la guía he probado a ponerlo como url en vez de como fichero en local.

Para ello he usado esta que he visto por internet:

https://raw.githubusercontent.com/davidmuma/EPG_dobleM/master/guiafanart_color.xml.gz

Parece que funciona. El único problema es que hay canales (Hollywood, Skyshowtime, paramount) que aparecen vacíos. Trataré de buscar otra.

El otro problema es que no aparece el botón reproducir para ver algo desde el principio.

**Comment by Paco8** [comment]
Haciendo pruebas he visto que da error de vez en cuando pero la mayoría de las veces funciona. ¿Quizás algún error momentáneo del servidor?
Seguiré haciendo pruebas.

**Comment by macamba** [comment]
He probado la version q pusiste, la plugin.video.movistarplus-0.8.15.zip y me va bien, hoy dia 4 de Marzo desde la EPG de PVR IPTV Simple me salen unos 4 dias, el dia 3, 4, 5, 6, aunq del 3 y del 6 solo algunos del final del dia y del inicio del dia.
Podrias añadir una opinión para q podamos añadir mas días a la EPG.xml hasta todo lo q haya en Movistar?, no se si seran 15 dias, supongo, 7 para atras del presente y otros 7 a futuro mas el presente
También estaria genial poder ver desde la EPG las caratulas, sinopsis y varios detalles de cada programa e incluso la opcion de grabar, aunq lo de grabar supongo q se antoja complicado si no hay muchas opciones q te ofrezca IPTV Simple

Gracias!

**Comment by macamba** [comment]
> En la versión 0.8.16 se puede elegir el número de días a exportar. Además se muestran mensajes indicando el progreso de la exportación.
> 
> No se pueden añadir la carátula ni la sinopsis porque la EPG no tiene esa información. Habría que ir descargando la información programa a programa y sería lentísimo.

Genial, lo acabo de probar. Si añado mas dias los añade al futuro, esta bien pero seria aun mas interesante también añadir dias del pasado para poder poner programas de días anteriores (U7D) desde la guia

**Comment by CarlosRodriguez1982** [comment]
Uy lo de que tenga los 7 ultimos dias es lo mas importante diría yo, ya que Movistar te permite ver los 7UD ; )

**Comment by Paco8** [comment]
¿De los días pasados no se encarga ya Kodi?
En ajustes, PVR y TV en directo, hay una opción para especificar el número de días pasados que se mostrarán en la guía.

**Comment by macamba** [comment]
> ¿De los días pasados no se encarga ya Kodi? En ajustes, PVR y TV en directo, hay una opción para especificar el número de días pasados que se mostrarán en la guía.

Si, eso es. Eso lo tengo puesto en 15 días desde el menu configuración de IPTV PVR Simple en el apartado Catchup y también en el tuyo, pero el fichero xml con la guía q genera tu addon no lo llena con los días pasados, solo un cacho del anterior y nada mas

**Comment by Paco8** [comment]
Me refiero a esta opción:

![Captura desde 2024-03-08 16-19-40](https://github.com/Paco8/plugin.video.movistarplus/assets/5084042/d75e62a7-b2e5-4990-b018-4932d5f8cf26)

Yo puedo ir hacia atrás en la guía hasta el lunes.

**Comment by macamba** [comment]
Ah!, no habia visto esa opción, lo he puesto a 7 dias para atras y 7 acia delante pero aún asi solo puedo ver como mucho un cachito de ayer en la Guia luego todo aparece sin nada
![20240308_163056](https://github.com/Paco8/plugin.video.movistarplus/assets/37476319/68a0e842-d25c-4a8c-8d99-1c3016a448ec)

**Comment by Paco8** [comment]
Tendrás que esperar varios días a que se vaya llenando la guía.

**Comment by macamba** [comment]
Lo raro es que llevo varios días con todo instalado pero nunca veo mas de un poco del dia anterior, no se me guarda lo viejo
