### ISSUE TITLE
Versión 075

### ISSUE THREAD

**Issue by perro130** [Paco8/plugin.video.movistarplus#3]
Que novedades lleva? gracias por tu trabajo

**Comment by Paco8** [comment]
En esta versión se trata de evitar que en los canales de fútbol los audios aparezcan como "desconocidos".

**Comment by perro130** [comment]
Gracias.
Sería chulo como idea ( no.se si es posible)
Que como.no.se ve el canal dazn pinchando en el canal no abriese la app de dazn o el addons de dazn previo intalado por nuestra parte.
Esta es posible o alguna cosa así ??
Lo dicho gracias crack

**Comment by Paco8** [comment]
¿No se ve dazn en movistar? En orange sí se ve.

**Comment by perro130** [comment]
No no se ve dazn la liga ,la fórmula 1 y eso sí 
Pera la liga no .
Por eso la idea .
Lo ves posible?

**Comment by perro130** [comment]
E. Orange si va 
Pero en Movistar no sale un canal.promocional
Pero si ver el canal como.tal

**Comment by Paco8** [comment]
Supongo que sí se podría hacer, lo que pasa es que yo no tengo dazn.

**Comment by perro130** [comment]
Que necesitas y lo vemos
Tines Telegram?

**Comment by Paco8** [comment]
Tengo discord: [Paco8#1670](https://discord.com/users/1027140600925016065)

**Comment by perro130** [comment]
@Perro13#1891 
Te estoy escribiendo pero no me deja  por qué Nome tienes. En la lista

**Comment by perro130** [comment]
Pincha y nos hablamos
