### ISSUE TITLE
Error al reproducir 

### ISSUE THREAD

**Issue by jabyg** [Paco8/plugin.video.movistarplus#33]
Buenas, no consigo ver ningún canal en directo, me carga bien los canales y la guía pero cuando le doy a reproducir me dice que uno o mas items fallaron en la reproducción. Las grabaciones sin embargo si me deja verla sin problemas.

Estoy usando kodi 20.4 en un Chromecast TV

**Comment by Paco8** [comment]
A mí me va. A ver si ha sido un error temporal en el servidor. Prueba otra vez.
