### ISSUE TITLE
Pausa pequeña a los pocos segundos de iniciar el stream

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [Paco8/plugin.video.movistarplus#34]
Buenos dias.

Felicidades y gracias por tu trabajo Paco8.

No se si soy al unico al que le pasa pero cada vez que cambio de canal a los pocos segundos tengo una pausa de algunos segundos, no se si es pq esta llenando el buffer.

Un saludo.

**Comment by Paco8** [comment]
He visto esto en un fire stick con kodi 20. Mira en los ajustes del inputstream adaptive, creo que con algunos modos va mejor que con otros.

**Comment by CarlosRodriguez1982** [comment]
Ahh vale gracias.

**Comment by Paco8** [comment]
Una vez empieza la reproducción ya es cosa del inputstream adaptive, así que ahí ya no puedo hacer nada.
Lo único que te puedo decir es que mires a ver si con el kodi 19 te va mejor. Es la versión que uso en un Nvidia shield y va perfecto, sin parones.

**Comment by Asaitamantequera1** [comment]
Ok gracias lo probaré a ver que tal

**Comment by CarlosRodriguez1982** [comment]
> Ok gracias lo probaré a ver que tal

No he podido aguantar las ganas y efectivamente cuando te creaste la cuenta habia otra persona con tu mismo nick xD:

![image](https://github.com/Paco8/plugin.video.movistarplus/assets/16527967/dae9b646-2978-4247-ad3e-6884eb9a1d0d)

**Comment by Asaitamantequera1** [comment]
Probado con éxito en Kodi 19 efectivamente el problema es de Kodi 20. Paco8 eres un crack

**Comment by CarlosRodriguez1982** [comment]
Pues vaya habra que decirselo a los del Adapative input stream y que lo arregles, pq el Kodi 20 va muuucho mas rapido.

**Comment by CarlosRodriguez1982** [comment]
Gracias, a instalar Kodi 21.
