### ISSUE TITLE
No me muestra la lista de canales

### ISSUE THREAD

**Issue by chetex** [Paco8/plugin.video.movistarplus#36]
Hola Paco! Muchas gracias lo primero por el trabajo y tu tiempo para mantenerlo.

Tengo... 

plugin.video.movistarplus-0.8.16.zip
script.module.ttml2ssa-0.3.8.zip
kodi-20.5-Nexus-armeabi-v7a.apk

Instalación siguiendo tus pasos del readme. 

NO me muestra la lista de canales ni en el epg. 
SI que veo ultimas grabaciones, continuar viendo etc...

![image](https://github.com/Paco8/plugin.video.movistarplus/assets/3778410/92fb5396-5927-49f4-8134-5135263407e6)

![image](https://github.com/Paco8/plugin.video.movistarplus/assets/3778410/c3825f63-9d8e-448e-9cad-c4317a3064a2)

Me han pasado la versión plugin.video.movistarplus-0.8.14.zip y con esa si me va... ¿hay algún log donde se pueda ver el error y que le pasa? 

Muchas gracias

**Comment by Paco8** [comment]
Puede que haya sido un fallo temporal al descargar la lista de canales. Prueba otra vez.
