### ISSUE TITLE
No funciona la TV en directo 

### ISSUE THREAD

**Issue by piperoddick** [Paco8/plugin.video.movistarplus#37]
Buenas Paco8,
Acabo de instalar el Addon pero no es posible reproducir la TV en directo ya que aparece el error de "Reproducción de lista abortada".
Sin embargo si es posible ver la TV a la carta.
Alguna sugerencia?

Add-on Movistar+ : 0.7.9
Kodi: 20.3 (20.3.0)

Muchas gracias por adelantado :)

**Comment by Paco8** [comment]
Instala la última versión y mira si te sigue pasando:
https://github.com/Paco8/plugin.video.movistarplus/releases

**Comment by piperoddick** [comment]
Muchísimas gracias! Ahora con la última versión ya funciona 🙂
