### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by toinmoreno** [Paco8/plugin.video.movistarplus#39]
hola al iniciar me dice :
server error while reading data

a que es debido?
Gracias.

**Comment by Paco8** [comment]
Pues lo acabo de probar y a mí no me pasa. Prueba otra vez, quizás haya sido un fallo puntual de sus servidores.

**Comment by toinmoreno** [comment]
Ya está solucionado ,volvi a logearme con correo y contraseña y funcione perfectamente.
muchas gracias por tu atención.
Un saludo.
