### ISSUE TITLE
Se muestra un número de identificación en los canales de fútbol.

### ISSUE THREAD

**Issue by RafaelR11** [Paco8/plugin.video.movistarplus#40]
En anteriores versiones del add-on no se muestra y no hay forma de desactivarlo y a veces es algo molesto durante los directos.

**Comment by Paco8** [comment]
La aplicación oficial también muestra el número, creo que es fundamentalmente para evitar que los bares usen un abono particular en lugar del abono para bares. 
Creo que es importante que el addon también lo haga para evitar que se use para hacer trampa, ya que eso podría provocar que el operador tomara medidas para que este addon no funcione.

**Comment by Tarraco1** [comment]
Gracias por la respuesta..!!
