### ISSUE TITLE
Error al exportar guía: “object is not callable”

### ISSUE THREAD

**Issue by dekom7** [Paco8/plugin.video.movistarplus#44]
Kodi 21.0.1
Addon Movistar+ 0.8.18
O.S. Android TV 12 (Chromecast)
Lo he probado en otro dispositivo con Android TV 10 (Sony Bravia) y va bien.

Al exportar la guía desde la opción de “Exportar los canales y la guía ahora” sale un error. Genera correctamente el fichero de los canales, pero luego al general el fichero con la guía sale un mensaje en pantalla: “Error Movistar+ Revise la información de registro”

Resumen del contenido del registro:
   EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
   Error Type: <class 'TypeError'>
   Error Contents: 'NoneType' object is not callable
   TypeError: 'NoneType' object is not callable

[Kodi error.log](https://github.com/Paco8/plugin.video.movistarplus/files/15189965/Kodi.error.log)

**Comment by Paco8** [comment]
El caso es que a mí no me da error, aunque alguna vez sí lo he visto.
Quizás sean fallos temporales en el servidor.
