### ISSUE TITLE
Al reproducir se cierra Kodi

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [Paco8/plugin.video.movistarplus#47]
Hola Paco.

Desde hace unos 3 dias se me cierra el Kodi al poner un canal o vod? A nadie le ocurre?

He probado en otro ordenador instalando Kodi con movistar desde cero (sin configurar iptv nisiqueira) y ocurre lo mismo. Instalado tambien desde repositorio que por cierto me sale Improved subtitles 0.3.9 y en github aparece la 0.3.8.

Un saludo.

**Comment by Paco8** [comment]
A mí no me pasa. ¿Qué versión de kodi tienes?

**Comment by Paco8** [comment]
¿Qué sistema operativo tienen esos ordenadores?

**Comment by CarlosRodriguez1982** [comment]
Windows 10 y Windows 11.

**Comment by Paco8** [comment]
Es un fallo de la última versión del inputstream adaptive que salió hace unos días.
Ya está reportado aquí:
https://github.com/xbmc/inputstream.adaptive/issues/1589

Se puede solucionar reinstalando la versión anterior:
https://mirrors.kodi.tv/addons/omega/inputstream.adaptive+windows-x86_64/inputstream.adaptive-21.4.9.zip

**Comment by CarlosRodriguez1982** [comment]
Muchas gracias. La verdad es que es vergonzoso, la industria tira cada una por su lado, y vosotros los desarrolladores tratando de hacerlas accesibles sin su ayuda... Es en este tipo de cosas en las que debería haber regulación, y no en hacernos perder el tiempo aceptando las malditas cookies ; ).

**Comment by Floyd77** [comment]
En el hilo que cita @Paco8 acaban de comentar que se soluciona instalando la última versión de Microsoft Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

Fuente: https://github.com/xbmc/inputstream.adaptive/issues/1589#issuecomment-2198234467
