### ISSUE TITLE
Error 4006 al intentar reproducir segundo capítulo

### ISSUE THREAD

**Issue by carlos-3210** [Paco8/plugin.video.movistarplus#49]
Buenos días, acabo de contribuir al proyecto con un coffee, y quería indicar un pequeño fallo, pero que no me supone mayor problema, es para mejorar si se puede.

Tengo puesto mi usuario y contraseña, y cuando busco alguna serie puedo ver el capítulo correctamente, y aunque pare y busque otro contenido, sigue funcionando. Pero si veo el capítulo completo, cuando quiero ver el siguiente u otro contenido, me salta en Kodi; "Error 4006: Invalid request". Y por más que intento, sigue saliendo el error. La única solución es salir de Kodi y volver a entrar. Entiendo que es que pasado el tiempo, se pierde la sesión, pero a ver si tiene solución.

La versión de Kodi es la 19.5 y está instalado en un tvbox con Android 5,1.  Adjunto el log del momento del error (he borrado la parte que pone token por si es información privada) y el pantallazo del error, Muchas gracias de nuevo. 

[-----> Archivo log error.txt](https://github.com/user-attachments/files/16726957/error.txt)

![Screenshot_2024-08-22-13-15-23](https://github.com/user-attachments/assets/fa281832-ed31-4dd2-aca0-d55882b1a1fc)

**Comment by Paco8** [comment]
Pues he probado en Kodi 19 en el PC y ese problema no me ocurre. Le doy a play a un episodio, voy hasta el final, espero a que acabe y le doy a otro episodio, y se ve, no me da error :confused:

**Comment by carlos-3210** [comment]
Bueno muchas gracias de todas formas por probarlo. De hecho he recordado que cuando instalé el addon, entré por primera vez y me logué y ya me daba error al reproducir por primera vez. Salí de Kodi, volví a entrar y ya funcionaba. Y luego detecté el error que reporté, que tras los 50 minutos que dura un capítulo, al querer reproducir el siguiente. Está claro que es algo que debo tener yo en mi instalación, porque nadie lo ha reportado. De todas formas me hace el apaño, porque Movistar acaba de bloquear el acceso a su app a Android 5 y 6 en los tvbox. Un saludo!

**Comment by Paco8** [comment]
¿Este problema te ocurre siempre o solo de vez en cuando?

**Comment by carlos-3210** [comment]
Buenas de nuevo. Lo he instalado hace poco pero de momento falla siempre. Es decir, al entrar en Kodi puedo ver cualquier contenido sin problema, incluso puedo parar y ver otro contenido. Pero si veo el capítulo completo, 50 minutos, al terminar ya no me deja ver el siguiente ni ningún otro contenido, hasta que salgo de Kodi y vuelvo a entrar.

**Comment by Paco8** [comment]
¿Al acabar el capítulo le das a stop, seleccionas el siguiente capítulo y le das a play, o usas la opción del menú contextual de "reproducir desde aquí" para que se reproduzca el siguiente capítulo automáticamente?

¿Y si desactivas la opción de "usar proxy para la licencia" en los ajustes de addon también pasa?

**Comment by carlos-3210** [comment]
Mmm a ver cómo lo explico... Al acabar el capítulo, dejo que termine por si solo, por lo que vuelve a la lista de capítulos. Y para reproducir el siguiente hago un click normal el el capítulo que quiero. He visto que si presiono unos segundos z sale un menú contextual con más opciones, pero eso no lo he usado.
Si desactivo lo de "usar proxy para la licencia" ya da error siempre en cualquier caso, ya no pone lo del 4006 pero sí dice "Reproducción de lista abortada. Uno o más elementos fallaron al reproducir. Revise el registro para obtener más información acerca de este mensaje".

**Comment by Paco8** [comment]
Creo que el error 4006 ocurre si se intenta reutilizar un token, por lo que parece que el addon está intentando usar el mismo token para los dos capítulos. Lo que no sé es cómo puede ocurrir eso.

Necesitaría que me mandes un log más largo, cuando empiezas a reproducir el primer capítulo hasta que intentas reproducir el segundo y da error.

**Comment by carlos-3210** [comment]
Muchas gracias Paco, aquí te mando adjunto el log que me has pedido, Para que te sea más sencillo localizar los eventos, te pongo por aquí los pasos que seguí en Kodi y que se verán reflejados en el LOG. Pero ya te digo que no quiero complicarte la vida, pero también me gusta investigar los errores como ves, y si te puede valer para mejorar el addon... Muchas gracias de nuevo y un saludo.

11:15:00- Entro en Kodi
11:15:30- Entro en tu addon de M+ en dispositivos
11:16:10- Ejecuto el cap 4 de la temporada 2 de Rapa. Lo dejo que se reproduzca entero, dura 51:29 minutos
12:07:58- Termina el capítulo y se para por sí solo, volviendo al listado de capítulos de la T2
12:08:30- Intento ejecutar el siguiente capítulo, el 5, y da error el 4006 a las 12:08:49
12:09:20- Salgo de Kodi.
[Log adjunto---->kodi2.txt](https://github.com/user-attachments/files/16747658/kodi2.txt)

**Comment by Paco8** [comment]
Pues no está usando el mismo token, así que eso es correcto.
¿Te ocurre con todas las series?
Si empiezas a reproducir un episodio, lo paras y le das play al siguiente ¿también da error?
¿Has mirado si en algún otro dispositivo (un móvil, por ejemplo) también ocurre lo mismo?

**Comment by carlos-3210** [comment]
> Pues no está usando el mismo token, así que eso es correcto. ¿Te ocurre con todas las series?

Sí, he probado con otras y es igual 

>Si empiezas a reproducir un episodio, lo paras y le das play al siguiente ¿también da error? 

No, si empiezo a reproducir la serie y la paro, puedo reproducir de nuevo, pero si repito varías veces, termina dando el error 4006.

He hecho esta prueba: reproducir un capítulo e irlo parando pasando un tiempo a ver si me deja volver a reproducir. He detectado que si pasan unos 3-4 minutos, ya da el error.

>¿Has mirado si en algún otro dispositivo (un móvil, por ejemplo) también ocurre lo mismo?
De momento no he hecho la prueba.

**Comment by Paco8** [comment]
Y si intentas reproducir el mismo episodio ¿te deja o también da error?

**Comment by Paco8** [comment]
Al final he conseguido reproducir el problema en kodi 19 en un Android TV, pero no con kodi 21.
Seguiré investigando a ver si consigo averiguar por qué pasa esto.

**Comment by carlos-3210** [comment]
Hola Paco, aunque ya lo has conseguido reproducir tú, te contesto a lo último... Una vez que da el error 4006, ya deja de funcionar totalmente, ya sea el mismo capítulo u otro capítulo de la misma serie, o de otra cualquiera. Ya la única solución es salir y volver a entrar en Kodi. Te recuerdo que yo tengo Kodi 19.5 en un tvbox Android 5.1 (no es Android TV). ¡Un saludo!

**Comment by Paco8** [comment]
Creo que he identificado el problema. ¿Puedes probar si esta versión lo soluciona?

[plugin.video.movistarplus-0.9.4-mod1.zip](https://github.com/user-attachments/files/16762219/plugin.video.movistarplus-0.9.4-mod1.zip)

**Comment by carlos-3210** [comment]
Hola Paco, muchas gracias! Parece que has dado con la tecla...

Nada más instalar la nueva versión ya me dio buena sensación, porque con la versión anterior me daba error la primera vez y tuve que reiniciar Kodi, esta vez no. Y me he visto un capítulo de 50 minutos y al terminar, he podido iniciar el siguiente...

No sé si vas a comentar lo que has tocado, pero bueno lo importante es que funciona. Muchas gracias de nuevo y seguiré disfrutando de M+ gracias a ti.

Un saludo.

**Comment by Paco8** [comment]
El problema era que una parte del código podía estar usando un token expirado.

**Comment by carlos-3210** [comment]
Muchas gracias, al final es lo que tú sospechabas, lo del token reutilizado... Muchas gracias de nuevo, y me alegro de haber podido ayudar un poquito 😏
