### ISSUE TITLE
Ultima version no funciona... 

### ISSUE THREAD

**Issue by vdias** [Paco8/plugin.video.movistarplus#5]
La acabo de actualizar, pero no abre ningún canal... he intentado restabelecer sesión, pero sigue igual...

**Comment by Paco8** [comment]
Mira a ver si funciona la versión 0.7.11.

**Comment by vdias** [comment]
Instalacion limpia de kodi y ultima versión addon y sigue sin funcionar... ¿como activo y veo los logs?

**Comment by vdias** [comment]
Error usuario. No era incidencia real.
