### ISSUE TITLE
Añadir de nuevo la función "Informar de las sesiones a los servidores"

### ISSUE THREAD

**Issue by RafaelR11** [Paco8/plugin.video.movistarplus#51]
Hola Paco, ¿podrías añadir de nuevo la función "Informar de las sesiones a los servidores"?,por favor, es porque antes yo, al desactivar esa función del addon en los ajustes, podía ver dos eventos a la vez en dos dispositivos o más fuera de casa, ya no me deja. Por ejemplo podía ver dos partidos de liga a la vez uno en la Smart TV con Kodi y otro en mi portátil con Kodi, pero ahora me sale el error de Forbidden de haber superado los dispositivos " OUT of Home", gracias y un saludo.

**Comment by Paco8** [comment]
Si tenías esa opción desactivada, seguirá estando desactivada, ya que el código que controla esa opción no se ha borrado y sigue funcionando.
