### ISSUE TITLE
[1080p/4K] Forzar resolucion?

### ISSUE THREAD

**Issue by Cachiputi** [Paco8/plugin.video.movistarplus#54]
Hola de nuevo @Paco8 

Es posible en el Addon forzar a un mínimo de 1080p la resolución de los canales en directo y los programas/pelis y tal? Si la conexión contratada lo permite claro.
Entiendo que para 1080p con 100mb reales contratados debería valer, cierto?
Y el poder poner en un ajuste como preferible 4K y que si el canal o video no esta en esa resolución que automáticamente se ponga en la resolución mas alta posible?
No se el porque, pero con una conexión de 300Mb de Fibra y usando el Chromcast 4K via HUB por RJ45 en la TV en directo, todos los canales se quedaban en 720p.

Gracias.

**Comment by Paco8** [comment]
Para eso tienes que mirar la configuración del inputstream adaptive. Ahí puedes elegir la resolución que quieres que se use.
