### ISSUE TITLE
Versión 9.8 no guarda lista de canales IPTV

### ISSUE THREAD

**Issue by macamba** [Paco8/plugin.video.movistarplus#56]
Buenas,

La nueva version 9.8 no guarda la lista de canales IPTV, también me ha extrañado q ahora no deje indicar en q carpeta guardar la lista de canales M3U ni la guia EPG

Saludos

**Comment by Paco8** [comment]
La nueva versión guarda la lista de canales y la epg en la carpeta de configuración del addon, así que ya no es necesario decirle donde guardarlos. Pero tienes que darle a la opción "Crear configuración para IPTV Simple" para que ese addon sepa dónde están.

**Comment by macamba** [comment]
> La nueva versión guarda la lista de canales y la epg en la carpeta de configuración del addon, así que ya no es necesario decirle donde guardarlos. Pero tienes que darle a la opción "Crear configuración para IPTV Simple" para que ese addon sepa dónde están.

Gracias!, siguiendo tus pasos ahora si funciona

Saludos
