### ISSUE TITLE
Programa aun no finalizado pero puesto desde el principio barra de tiempo siempre 1 hora

### ISSUE THREAD

**Issue by macamba** [Paco8/plugin.video.movistarplus#57]
Buenas,

Me pasa q cuando quiero ver un programa q aun no ha finalizado pero lo pongo desde el principio me encuentro q la barra de tiempo es de 1 hora aunq el programa dure mas q eso

El mayor problema viene cuando quiero saltarme los anuncios pero ya no me deja dar saltos cuando llego a la hora de emision

![20240913_160637](https://github.com/user-attachments/assets/d1f3df8a-d622-435d-b4bc-9db5961fb284)

Saludos

**Comment by Paco8** [comment]
Ya lo veo pero me parece que es así. Eso son los manifiestos que devuelve el servidor de movistar+

**Comment by carlos-3210** [comment]
Por si sirve de ayuda, a mi me pasa eso en la aplicación oficial en el móvil, sin embargo en el decodificador no hay ese límite de una hora.

**Comment by macamba** [comment]
Parece q el problema lo causa directamente los servidores de Movistar.
Comp sugerencia se podria corregir los metadatos de aquellos programas cuyo final de emisión sea mayor al presente?

**Comment by Paco8** [comment]
Creo que sí se podría arreglar, sería un poco lioso pero creo que es posible.

**Comment by Paco8** [comment]
Pues me temo que no se puede. Aunque modifique la hora a la que termina el programa, el kodi sigue marcando una duración de 1 hora.

**Comment by Uukrull** [comment]
En el mpd está limitado a una hora: timeShiftBufferDepth="PT3600S" y, si existe ese valor, inputstream.adaptive lo usa como duración máxima:

https://github.com/xbmc/inputstream.adaptive/blob/2147f080462d10ccb315eec3074a12db3b99cab5/src/parser/DASHTree.cpp#L290-L291

Una solución sería comentar esas dos líneas para que la duración máxima se calcule con el número de periodos disponibles, ignorando timeShiftBufferDepth. Yo lo tengo así pero no deja de ser una ñapa y dudo mucho que CastagnaIT estuviera por la labor.

**Comment by Paco8** [comment]
Si ese es el problema creo que entonces se podría sustituir ese número por otro más alto desde el proxy del addon.

**Comment by Uukrull** [comment]
Si el addon puede modificar el mpd, entonces sí.

**Comment by Paco8** [comment]
He hecho ese cambio en la versión 0.9.12. Ahora en vez de ser una hora serán 3.

**Comment by macamba** [comment]
Genial!, lo he estado probando y funciona de lujo asi!  👍

Gracias!
