### ISSUE TITLE
Reproducir desde EPG

### ISSUE THREAD

**Issue by CarlosRodriguez1982** [Paco8/plugin.video.movistarplus#59]
Ahora con la nueva versión me da los detalles completos en el EPG. Lo unico que solo me da la opcion de cambiar canal, no de reproducir un programa (a traves del addon funciona). Por cierto antes tampoco me dejaba si habia pasado mas 2 o 3 dias.

Una pregunta, ¿para descargar la EPG de los 7 dias anteriores es necesario haberlas cargado antes de que pase el día?
Lo digo porque solo se me descargan los 7 proximos dias, es decir que si estoy por ejemplo 10 dias sin abrir el Kodi y lo abro, se supone no tendre el EPG de los ultimos días 3 dias. En la web de Movistar sí que muestra el EPG de los 7 días anteriores, pero no se si el plugin es capaz de acceder a el.

Muchas gracias por tu gran trabajo.

**Comment by Paco8** [comment]
La verdad es que aún no he tenido tiempo de mirar si con la guía online se puede configurar la cosa para que se puedan ver los programas emitidos.

Para que la guía del IPTV Simple muestre días pasados creo que eso lo debes configurar en el apartado "PVR y TV en directo" del kodi, en la opción guía, "días pasados a mostrar".

**Comment by CarlosRodriguez1982** [comment]
Si eso ya lo tengo activado, por ejemplo ahora solo me muestra desde el dia 11, que es el dia que lo reinstalé, no baja nada por atrasado, solo lo futuro.

> La verdad es que aún no he tenido tiempo de mirar si con la guía online se puede configurar la cosa para que se puedan ver los programas emitidos.

Vaya espero que sí, porque esa es la gracia de la parrilla, poder ver rapidamente cualquier cosa de los U7D.

**Comment by Paco8** [comment]
En la versión 0.9.11 ya es posible ver programas desde la guía online, pero hay que volver a darle a la opción "crear configuración para iptv simple" ya que hay que modificar algunas cosas.

**Comment by CarlosRodriguez1982** [comment]
Menos mal, espero se tire Movistar un tiempo grande sin tocar la guia para no darte a ti mas trabajo xD.
