### ISSUE TITLE
Problema iniciar sesion.

### ISSUE THREAD

**Issue by puntoCL** [Paco8/plugin.video.movistarplus#6]
Muchas gracias por tu trabajo. Estuve probando el addons y al intentar iniciar sesion me salta el un alerta de error indicando "error al iniciar sesión". desconozco si soy yo.

**Comment by Paco8** [comment]
Lo acabo de probar y a mí me sigue funcionando.

**Comment by puntoCL** [comment]
acabo de darme cuenta dentro del código que hace referencia a 

 'Origin': 'https://ver.movistarplus.es',
 'Referer': 'https://ver.movistarplus.es/',

Aca en chile es https://movistartv.cl

**Comment by Paco8** [comment]
El addon es para Movistar+ España.
