### ISSUE TITLE
Dolby 5.1

### ISSUE THREAD

**Issue by mmt1466** [Paco8/plugin.video.movistarplus#63]
Hola
Desde version 0.9.14 pierdo audio 5.1.
Instalo versiones anteriores y funciona.
Muchas Gracias.
PD Tengo contratado paquete HD 9,95€

**Comment by mmt1466** [comment]
En version  0.10.0. sigue pasando.
Seguiré con la 0.9.13.
Muchas Gracias.

**Comment by mmt1466** [comment]
En version 0.10.1. sigue pasando.
_¿Cual puede ser la causa?_
Seguiré con la 0.9.13.
Muchas Gracias.

**Comment by Paco8** [comment]
¿Me puedes decir una película o serie que tenga sonido 5.1 para que lo pueda mirar?

**Comment by mmt1466** [comment]
El 99% de las pelis tienen audio 5.1.
Mira en a la carta, cualquiera de la seccion "Un estreno de cine al dia", o cualquier serie actual.
Muchas gracias.

**Comment by Paco8** [comment]
Creo que está arreglado en la versión 0.10.2.

**Comment by mmt1466** [comment]
Probada v. 0.10.2.
Funciona perfectamente.
Muchas gracias por tu trabajo.
