### ISSUE TITLE
RESUELTO PROBLEMA: SESION HA CADUCADO

### ISSUE THREAD

**Issue by pcc995** [Paco8/plugin.video.movistarplus#69]
Desde hace dias al entrar da ERROR: LA SESION HA CADUCADO 

He instalado la última versión, he desinstalado y vuelvo a instalar y sigue pasando.

Hay solución?

gracias

**Comment by pcc995** [comment]
Pienso que Movistar ha hecho cambios y obliga a logarse cada vez que detecta algo anormal, pide escanear un bidi o introducir un código en una página de login y eso debe afectar a la App de paco8.

**Comment by Paco8** [comment]
La sesión caduca pasados unos días y hay que volver a iniciar sesión, con usuario y clave.

**Comment by pcc995** [comment]
Inicio sesión con fichero key pero sigue fallando, probaré a introducirla manual.

Gracias

De: Paco8 ***@***.***>
Enviado el: viernes, 8 de noviembre de 2024 0:16
Para: Paco8/plugin.video.movistarplus ***@***.***>
CC: pcc995 ***@***.***>; Author ***@***.***>
Asunto: Re: [Paco8/plugin.video.movistarplus] NO FUNCIONA: SESION HA CADUCADO (Issue #69)


La sesión caduca pasados unos días y hay que volver a iniciar sesión, con usuario y clave.

**Comment by Paco8** [comment]
Es que es posible que el fichero key haya caducado también.

**Comment by pcc995** [comment]
Vale, esta tarde pruebo a ver.

Muchas gracias
________________________________
De: Paco8 ***@***.***>
Enviado: Friday, November 8, 2024 9:00:43 AM
Para: Paco8/plugin.video.movistarplus ***@***.***>
Cc: pcc995 ***@***.***>; Author ***@***.***>
Asunto: Re: [Paco8/plugin.video.movistarplus] NO FUNCIONA: SESION HA CADUCADO (Issue #69)


Es que es posible que el fichero key haya caducado también.

**Comment by pcc995** [comment]
Llevo días dándole vueltas al fallo y no lo resolvía por empeñarme en no teclear el usuario y la clave y usar el fichero key pues no pensé que pudiera caducar el fichero! Cachis!

Ya está resuelto!

Muchas gracias


________________________________
De: Paco8 ***@***.***>
Enviado: viernes, noviembre 8, 2024 9:00 a. m.
Para: Paco8/plugin.video.movistarplus ***@***.***>
CC: pcc995 ***@***.***>; Author ***@***.***>
Asunto: Re: [Paco8/plugin.video.movistarplus] NO FUNCIONA: SESION HA CADUCADO (Issue #69)


Es que es posible que el fichero key haya caducado también.
