### ISSUE TITLE
Me imagino que es para OTT

### ISSUE THREAD

**Issue by macamba** [Paco8/plugin.video.movistarplus#7]
Hola!
Muchísimas gracias por compartir esta clase de cosas q nos dan mucha mas libertad a los usuarios para poder controlar y visualizar el contenido de los proveedores

Tengo varias preguntas;
 * Se puede ver el contenido en varios aparatos al mismo tiempo en casa o solo la cantidad de dispositivos q permite el proveedor?
 * Hay pretension de hacer lo mismo pero para Movistar IPTV, la señal multicast q llega al deco de Movistar?. Para este punto yo programe un deco virtual en java/android y todo me funcionaba genial hasta q metieron la señal codificada, por lo q si quieres emprender a hacerlo yo te puedo pasar todo el codigo q tengo -> sacar listas de canales, guia, listas de grabaciones, U7D y los protocolos de cada cosa
 * Y por curiosidad hay posibilidad de hacer lo mismo para la OTT de Vodafone?

Saludos

**Comment by Paco8** [comment]
> * Se puede ver el contenido en varios aparatos al mismo tiempo en casa o solo la cantidad de dispositivos q permite el proveedor?

Si se desactiva la opción "Informar de las sesiones a los servidores" sí se puede, aunque el truco no funciona con los contenidos de TV a la carta.

> * Hay pretension de hacer lo mismo pero para Movistar IPTV, la señal multicast q llega al deco de Movistar?. Para este punto yo programe un deco virtual en java/android y todo me funcionaba genial hasta q metieron la señal codificada, por lo q si quieres emprender a hacerlo yo te puedo pasar todo el codigo q tengo -> sacar listas de canales, guia, listas de grabaciones, U7D y los protocolos de cada cosa

Como comento [aquí](https://github.com/Paco8/plugin.video.movistarplus/issues/1) yo en realidad no estoy abonado a movistar, y creo que para poder ver los canales IPTV hay que estarlo ¿no?


> * Y por curiosidad hay posibilidad de hacer lo mismo para la OTT de Vodafone?

Pues no sé, supongo que sí.

**Comment by macamba** [comment]
Hola Paco,

Para Movistar por Multicast al deco hay q estar abonado para q te llegue la señal.
Ya no estoy con Movistar sino sin duda te pasaria el token o lo q necesites. Me cambie a Vodafone, asiq si en algun momento vas a desarrollar algo para la OTT de Vodafone te podria mandar el codigo token o lo q haga falta para su desarrollo

Saludos

**Comment by vdias** [comment]
Yo si estoy abonado… pero no creo que sea así de sencillo sacar la clave que usan para codificar los canales por multicast…

**Comment by macamba** [comment]
Con respecto a la clave de los canales ni idea, ni teniendola sabria por donde empezar, en cambio si recuerdo q en las solicitudes de VOD si que venia un parametro que era una key, si no recuerdo mal era de 32 caracteres hexadecimal, pero ni idea como decodificar las partes del stream de video en TS
