### ISSUE TITLE
Xbox s no me va

### ISSUE THREAD

**Issue by chusan1** [Paco8/plugin.video.movistarplus#70]
Buenas lo he instalado y no me deja verlo me sale error 
![IMG_0095](https://github.com/user-attachments/assets/c5f97c72-a637-4e56-8918-c79eafa3dd88)
![IMG_0094](https://github.com/user-attachments/assets/f05259d1-5130-44de-b245-76ce242c1919)

alguna idea??

**Comment by Paco8** [comment]
No tengo xbox pero me pareció haber leído alguna vez que widevine no se puede instalar en xbox (o es complicado hacerlo). Sin widevine el addon no puede funcionar.

**Comment by chusan1** [comment]
Al instalar el admón en el PC me he dado cuenta de eso que dices, me ha pedido instalarlo después… gracias.  Miraré a ver.  Un saludo
