### ISSUE TITLE
Soporte IPTV por html en lugar de local

### ISSUE THREAD

**Issue by macamba** [Paco8/plugin.video.movistarplus#8]
Hola Paco,

Ojeando la documentación para el soporte para IPTV veo que generas tanto la lista de canales como el epg localmente como archivos movistar-channels.m3u8 y movistar-epg.xml, pero seria mucho mas versatil poder acceder a esos archivos solicitandolos al servidor q montas con tu addon por html
Como te comente en otro hilo yo en su dia me programe un programa servidor en android q descubria Movistar TV q tuvieses contratado y una de las opciones q tenia era poder proporcionar tanto la lista de canales como el epg atraves de una solicitud html. Esto es muy práctico porq yo solia montar el servidor en el androd TV mas potente y este podia servir todo el servicio al resto de la casa o tambien si estoy fuera.
Y tenia 2 tipos de solicitudes una local por ejemplo http://ip-local-servidor:21500/movistar-channels-local.m3u8 en esta las IPs de los streams apuntan a la IP local del servidor de la red de casa y cualquier otro dispositivo alcanzara al servidor sin problema y otra solicitud si estoy fuera de casa algo como esto http://ip-publica-servidor:21500/movistar-channels-external.m3u8 donde las IPs de los streams serian la pública con la q salgo a internet o la publica del router para poder acceder desde fuera de casa siempre y cuando el puerto q se use este abierto en el router, en este ejemplo el 21500

No se si me explicado bien, sino me dices

Saludos

**Comment by Paco8** [comment]
Habría dos problemas: uno es que el puerto que usa el servidor no es fijo. Se trata de usar un puerto predeterminado pero si está ocupado se usa otro.
Otro inconveniente es que para configurar el IPTV Simple el usuario debería entonces teclear las dos url para los canales y la epg, que son bastante largas, y hacerlo en un Android TV letra a letra es un fastidio.

Esto se podría solucionar generando automáticamente la configuración para IPTV Simple pero cuando lo programé tampoco quise complicarme la vida.

**Comment by macamba** [comment]
Claro, a eso me refiero, que se generen las listas para IPTV Simple, y desde este IPTV Simple poner las url de cada cosa, solo seria una vez y listo, solo habria q corregir la IP publica en los casos de los dispositivos q esten fuera de casa y solo seria la IP de la url en los casos q el router cambie de IP

**Comment by TSCNEO** [comment]
> Hola Paco,
> 
> Ojeando la documentación para el soporte para IPTV veo que generas tanto la lista de canales como el epg localmente como archivos movistar-channels.m3u8 y movistar-epg.xml, pero seria mucho mas versatil poder acceder a esos archivos solicitandolos al servidor q montas con tu addon por html Como te comente en otro hilo yo en su dia me programe un programa servidor en android q descubria Movistar TV q tuvieses contratado y una de las opciones q tenia era poder proporcionar tanto la lista de canales como el epg atraves de una solicitud html. Esto es muy práctico porq yo solia montar el servidor en el androd TV mas potente y este podia servir todo el servicio al resto de la casa o tambien si estoy fuera. Y tenia 2 tipos de solicitudes una local por ejemplo http://ip-local-servidor:21500/movistar-channels-local.m3u8 en esta las IPs de los streams apuntan a la IP local del servidor de la red de casa y cualquier otro dispositivo alcanzara al servidor sin problema y otra solicitud si estoy fuera de casa algo como esto http://ip-publica-servidor:21500/movistar-channels-external.m3u8 donde las IPs de los streams serian la pública con la q salgo a internet o la publica del router para poder acceder desde fuera de casa siempre y cuando el puerto q se use este abierto en el router, en este ejemplo el 21500
> 
> No se si me explicado bien, sino me dices
> 
> Saludos

Me parece súper interesante tu proyecto. Se podría poner en vez de IP Publica un DDNS y así no cambiaría la IP. ¿es posible que hagas pública tu app?

Muchas gracias!

**Comment by vdias** [comment]
No sé si he entendido bien tu idea… pero lo único que quieres compartir son los dos ficheros verdad? No es más sencillo subirlos a algún vps o storage público, evitando abrir puertas en tu casa?

**Comment by macamba** [comment]
Hola Paco,

Me han dejado unas credenciales para probar el Addon y funciona fenomenal, un gran trabajazo lo q has hecho con este addon
He ojeado el fichero movistar-channels.m3u8 y veo q no hay Streams sino llamadas al plugin con unos parámetros q es una url, pero esta no funciona si la pongo en un programa externo como el VLC. Podrias hacer que fueran stream urls que funcionasen externamente? asi podria usar los enlaces en casi cualquier dispositivo de la casa (moviles viejos y modernos, PCs, SmartTVs, ...). Esto ya seria la guinda del pastel 😀

Gracias y saludos

**Comment by Paco8** [comment]
Me temo que no se puede. Los streams van codificados y hay que pasarle un token (entre otras cosas) al inputstream adaptive del kodi para que los decodifique.

**Comment by ManEtha** [comment]
> Habría dos problemas: uno es que el puerto que usa el servidor no es fijo. Se trata de usar un puerto predeterminado pero si está ocupado se usa otro. Otro inconveniente es que para configurar el IPTV Simple el usuario debería entonces teclear las dos url para los canales y la epg, que son bastante largas, y hacerlo en un Android TV letra a letra es un fastidio.
> 
> Esto se podría solucionar generando automáticamente la configuración para IPTV Simple pero cuando lo programé tampoco quise complicarme la vida.

Y bien que hiciste Paco, de esta forma los addons de Kodi se quedan en Kodi. Para lo otro ya están las IPTV.
